# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: SeriousBit.NetBalancer
PackageVersion: 10.5.3.3032
PackageLocale: en-US
Publisher: SeriousBit
PublisherUrl: https://seriousbit.com/
PublisherSupportUrl: https://seriousbit.com/contact
PrivacyUrl: https://seriousbit.com/privacypolicy.txt
Author: SeriousBit Srl
PackageName: NetBalancer
PackageUrl: https://netbalancer.com/download
License: Proprietary
LicenseUrl: https://seriousbit.com/tos.txt
Copyright: Copyright (c) Seriousbit Srl
ShortDescription: NetBalancer is an internet traffic control and monitoring tool
Description: 'NetBalancer is an internet traffic control and monitoring tool designed for Microsoft Windows 7, 8 and 10 (and their server variants) with native x64 support. With NetBalancer you can: Set a download and/or upload network priority or limit for any process, manage priorities and limits for each network adapter separately, define detailed network traffic rules, set global traffic limits, get detailed statistics and totals about your data usage, show network traffic in system tray and much more!'
Moniker: netbalancer
Tags:
- network-limiter
- network-monitor
- netmon
- data-saver
ReleaseNotes: https://netbalancer.com/news
ReleaseNotesUrl: https://netbalancer.com/news
ManifestType: defaultLocale
ManifestVersion: 1.1.0

