# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: Cisco.PacketTracer
PackageVersion: 8.1.1.0022
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0

